server:
  port: 9098

spring:
  application:
    name: schoolservice
  data:
    mongodb:
      uri: mongodb://localhost:27017  
      database: schoolservice
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin  

logging:
  level:
    com.schoolservice: INFO