apiVersion: v1
kind: Secret
metadata:
  name: mongodb-atlas-school  
type: Opaque
data:
  mongodb.uri.schools: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbkBjbHVzdGVyMC1oc3loMC5nY3AubW9uZ29kYi5uZXQvc2Nob29sc2VydmljZT9yZXRyeVdyaXRlcz10cnVl